spring:
  application:
    name: ipqcmBiz
  #数据库配置
  datasource:
    # 基础配置
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: C##IPQCM
    password: IPQCM_123
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20

# myBatis配置
mybatis:
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.th.iqpcmbiz.entity
  configuration:
    map-underscore-to-camel-case: true     # 开启驼峰命名映射
    default-fetch-size: 100                # 可选，调整批量查询性能
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 输出 SQL 日志

# 日志相关配置
logging:
  level:
    org.springframework: warn

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  # excludes: /system/notice/*
  # 匹配链接
  # urlPatterns: /system/*,/monitor/*,/tool/*

# 防止csrf攻击
csrf:
  # 过滤开关
  enabled: true
  # 白名单（多个用逗号分隔）
  whites:

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true