-- 工具表
CREATE TABLE TOOL_INFO (
    ID              NUMBER PRIMARY KEY,
    TOOL_CODE      VARCHAR2(50) NOT NULL UNIQUE,
    TOOL_NAME      VARCHAR2(100) NOT NULL,
    TOOL_TYPE      VARCHAR2(50),
    CABINET_NO     VARCHAR2(20),
    STATUS         VARCHAR2(20) DEFAULT 'available',
    SPECIFICATION  VARCHAR2(200),
    CREATE_TIME    DATE DEFAULT SYSDATE,
    UPDATE_TIME    DATE DEFAULT SYSDATE
);

CREATE SEQUENCE TOOL_INFO_SEQ START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE TOOL_INFO IS '工具信息表';
COMMENT ON COLUMN TOOL_INFO.TOOL_CODE IS '工具编号';
COMMENT ON COLUMN TOOL_INFO.TOOL_NAME IS '工具名称';
COMMENT ON COLUMN TOOL_INFO.TOOL_TYPE IS '工具类型';
COMMENT ON COLUMN TOOL_INFO.CABINET_NO IS '所属柜号';
COMMENT ON COLUMN TOOL_INFO.STATUS IS '状态(available/lend/maintenance)';
COMMENT ON COLUMN TOOL_INFO.SPECIFICATION IS '规格参数';

-- 借还记录表
CREATE TABLE BORROW_RECORD (
    ID              NUMBER PRIMARY KEY,
    TOOL_CODE      VARCHAR2(50) NOT NULL,
    USER_ID        VARCHAR2(50) NOT NULL,
    BORROW_TIME    DATE DEFAULT SYSDATE,
    RETURN_TIME    DATE,
    STATUS         VARCHAR2(20) DEFAULT 'borrowed',
    OPERATOR_TYPE  VARCHAR2(20)
);

CREATE SEQUENCE BORROW_RECORD_SEQ START WITH 1 INCREMENT BY 1;

CREATE INDEX IDX_BORROW_TOOL ON BORROW_RECORD(TOOL_CODE);
CREATE INDEX IDX_BORROW_USER ON BORROW_RECORD(USER_ID);
CREATE INDEX IDX_BORROW_TIME ON BORROW_RECORD(BORROW_TIME);

COMMENT ON TABLE BORROW_RECORD IS '工具借还记录表';
COMMENT ON COLUMN BORROW_RECORD.TOOL_CODE IS '工具编号';
COMMENT ON COLUMN BORROW_RECORD.USER_ID IS '借用人编号';
COMMENT ON COLUMN BORROW_RECORD.BORROW_TIME IS '借出时间';
COMMENT ON COLUMN BORROW_RECORD.RETURN_TIME IS '归还时间';
COMMENT ON COLUMN BORROW_RECORD.STATUS IS '状态(borrowed/returned)';
COMMENT ON COLUMN BORROW_RECORD.OPERATOR_TYPE IS '操作类型(borrow/return)';

-- 异常日志表
CREATE TABLE EXCEPTION_LOG (
    ID              NUMBER PRIMARY KEY,
    EXCEPTION_TYPE  VARCHAR2(50) NOT NULL,
    TOOL_CODE       VARCHAR2(50),
    USER_ID         VARCHAR2(50),
    DESCRIPTION     VARCHAR2(500),
    STATUS          VARCHAR2(20) DEFAULT 'pending',
    CREATE_TIME     DATE DEFAULT SYSDATE,
    HANDLE_TIME     DATE,
    HANDLER         VARCHAR2(50)
);

CREATE SEQUENCE EXCEPTION_LOG_SEQ START WITH 1 INCREMENT BY 1;

CREATE INDEX IDX_EXCEPTION_STATUS ON EXCEPTION_LOG(STATUS);
CREATE INDEX IDX_EXCEPTION_TIME ON EXCEPTION_LOG(CREATE_TIME);

COMMENT ON TABLE EXCEPTION_LOG IS '异常日志表';
COMMENT ON COLUMN EXCEPTION_LOG.EXCEPTION_TYPE IS '异常类型';
COMMENT ON COLUMN EXCEPTION_LOG.TOOL_CODE IS '工具编号';
COMMENT ON COLUMN EXCEPTION_LOG.USER_ID IS '用户编号';
COMMENT ON COLUMN EXCEPTION_LOG.DESCRIPTION IS '异常描述';
COMMENT ON COLUMN EXCEPTION_LOG.STATUS IS '状态(pending/handled)';
COMMENT ON COLUMN EXCEPTION_LOG.HANDLE_TIME IS '处理时间';
COMMENT ON COLUMN EXCEPTION_LOG.HANDLER IS '处理人';