-- 人脸特征表
CREATE TABLE FACE_FEATURE (
    ID              NUMBER PRIMARY KEY,
    USER_ID         VARCHAR2(50) NOT NULL,
    FACE_INDEX      NUMBER(2) DEFAULT 1,
    FEATURE_VECTOR  BLOB NOT NULL,
    FACE_IMAGE      BLOB,
    QUALITY_SCORE   FLOAT,
    THRESHOLD       FLOAT DEFAULT 0.4,
    CREATE_TIME     DATE DEFAULT SYSDATE,
    UNIQUE(USER_ID, FACE_INDEX)
);

CREATE INDEX IDX_FACE_USER ON FACE_FEATURE(USER_ID);

COMMENT ON TABLE FACE_FEATURE IS '人脸特征表';
COMMENT ON COLUMN FACE_FEATURE.USER_ID IS '用户ID';
COMMENT ON COLUMN FACE_FEATURE.FACE_INDEX IS '人脸序号(同一用户第几张)';
COMMENT ON COLUMN FACE_FEATURE.FEATURE_VECTOR IS 'SFace 128维特征向量';
COMMENT ON COLUMN FACE_FEATURE.FACE_IMAGE IS '裁剪后人脸图片';
COMMENT ON COLUMN FACE_FEATURE.QUALITY_SCORE IS '质量分数';
COMMENT ON COLUMN FACE_FEATURE.THRESHOLD IS '比对阈值';

-- 修改用户表，添加人脸字段
ALTER TABLE USER_INFO ADD (
    FACE_ENABLED    CHAR(1) DEFAULT '0',
    FACE_ENROLLED   CHAR(1) DEFAULT '0'
);

COMMENT ON COLUMN USER_INFO.FACE_ENABLED IS '是否启用人脸登录';
COMMENT ON COLUMN USER_INFO.FACE_ENROLLED IS '是否已录入人脸';

-- 创建序列
CREATE SEQUENCE FACE_FEATURE_SEQ START WITH 1 INCREMENT BY 1;