-- 登录Token表
CREATE TABLE LOGIN_TOKEN (
    ID              NUMBER PRIMARY KEY,
    USER_ID         VARCHAR2(50) NOT NULL,
    TOKEN           VARCHAR2(64) NOT NULL UNIQUE,
    LAST_ACTIVITY   DATE,
    CREATE_TIME     DATE DEFAULT SYSDATE,
    EXPIRE_TIME     DATE
);

CREATE SEQUENCE LOGIN_TOKEN_SEQ START WITH 1 INCREMENT BY 1;

CREATE INDEX IDX_LOGIN_TOKEN_TOKEN ON LOGIN_TOKEN(TOKEN);
CREATE INDEX IDX_LOGIN_TOKEN_USER ON LOGIN_TOKEN(USER_ID);

COMMENT ON TABLE LOGIN_TOKEN IS '登录Token表';
COMMENT ON COLUMN LOGIN_TOKEN.USER_ID IS '用户编号';
COMMENT ON COLUMN LOGIN_TOKEN.TOKEN IS '登录Token';
COMMENT ON COLUMN LOGIN_TOKEN.LAST_ACTIVITY IS '最后活动时间';
COMMENT ON COLUMN LOGIN_TOKEN.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN LOGIN_TOKEN.EXPIRE_TIME IS '过期时间';