-- =====================================================
-- 工具识别系统数据库改造脚本
-- 执行时间: 2026-05-11
-- =====================================================

-- =====================================================
-- 1. 修改 TOOL_INFO 表，添加 YOLO 识别类别字段
-- =====================================================
ALTER TABLE TOOL_INFO ADD RECOGNITION_TYPE VARCHAR2(50);

COMMENT ON COLUMN TOOL_INFO.RECOGNITION_TYPE IS 'YOLO识别类别(wrench/screwdriver/pliers)';

-- =====================================================
-- 2. 创建工具柜库存表 TOOL_CABINET_INVENTORY
-- 记录工具柜中每个位置的当前工具
-- =====================================================
CREATE TABLE TOOL_CABINET_INVENTORY (
    ID              NUMBER PRIMARY KEY,
    CABINET_NO      VARCHAR2(20) NOT NULL COMMENT '柜号',
    TOOL_CODE       VARCHAR2(50) NOT NULL COMMENT '工具编号',
    POSITION        VARCHAR2(20) NOT NULL COMMENT '柜门位置',
    STATUS          VARCHAR2(20) DEFAULT 'in_cabinet' COMMENT 'in_cabinet在柜中/empty空位',
    CREATE_TIME     DATE DEFAULT SYSDATE,
    UPDATE_TIME     DATE DEFAULT SYSDATE
);

COMMENT ON TABLE TOOL_CABINET_INVENTORY IS '工具柜库存表';
COMMENT ON COLUMN TOOL_CABINET_INVENTORY.CABINET_NO IS '柜号';
COMMENT ON COLUMN TOOL_CABINET_INVENTORY.TOOL_CODE IS '工具编号';
COMMENT ON COLUMN TOOL_CABINET_INVENTORY.POSITION IS '柜门位置';
COMMENT ON COLUMN TOOL_CABINET_INVENTORY.STATUS IS 'in_cabinet在柜中/empty空位';

-- 创建序列
CREATE SEQUENCE TOOL_CABINET_INVENTORY_SEQ START WITH 1 INCREMENT BY 1;

-- 创建索引
CREATE INDEX IDX_INVENTORY_CABINET ON TOOL_CABINET_INVENTORY(CABINET_NO);
CREATE INDEX IDX_INVENTORY_TOOL ON TOOL_CABINET_INVENTORY(TOOL_CODE);
CREATE INDEX IDX_INVENTORY_STATUS ON TOOL_CABINET_INVENTORY(STATUS);

-- =====================================================
-- 3. 创建工具柜快照表 TOOL_CABINET_SNAPSHOT
-- 记录借/还操作前后的工具柜状态，用于对比
-- =====================================================
CREATE TABLE TOOL_CABINET_SNAPSHOT (
    ID              NUMBER PRIMARY KEY,
    CABINET_NO      VARCHAR2(20) NOT NULL COMMENT '柜号',
    TOOL_CODE       VARCHAR2(50) NOT NULL COMMENT '工具编号',
    POSITION        VARCHAR2(20) NOT NULL COMMENT '柜门位置',
    SNAPSHOT_TYPE   VARCHAR2(20) NOT NULL COMMENT 'before借前快照/after借后快照',
    BORROW_RECORD_ID NUMBER COMMENT '关联的借还记录ID',
    CREATE_TIME     DATE DEFAULT SYSDATE
);

COMMENT ON TABLE TOOL_CABINET_SNAPSHOT IS '工具柜快照表';
COMMENT ON COLUMN TOOL_CABINET_SNAPSHOT.CABINET_NO IS '柜号';
COMMENT ON COLUMN TOOL_CABINET_SNAPSHOT.TOOL_CODE IS '工具编号';
COMMENT ON COLUMN TOOL_CABINET_SNAPSHOT.POSITION IS '柜门位置';
COMMENT ON COLUMN TOOL_CABINET_SNAPSHOT.SNAPSHOT_TYPE IS 'before借前/after借后';
COMMENT ON COLUMN TOOL_CABINET_SNAPSHOT.BORROW_RECORD_ID IS '关联的借还记录ID';

-- 创建序列
CREATE SEQUENCE TOOL_CABINET_SNAPSHOT_SEQ START WITH 1 INCREMENT BY 1;

-- 创建索引
CREATE INDEX IDX_SNAPSHOT_RECORD ON TOOL_CABINET_SNAPSHOT(BORROW_RECORD_ID);
CREATE INDEX IDX_SNAPSHOT_CABINET ON TOOL_CABINET_SNAPSHOT(CABINET_NO);
CREATE INDEX IDX_SNAPSHOT_TYPE ON TOOL_CABINET_SNAPSHOT(SNAPSHOT_TYPE);

-- =====================================================
-- 4. 初始化数据（示例：假设柜号001有3个位置）
-- =====================================================
-- 注意：实际数据需要根据真实的工具柜布局来初始化
-- 以下为示例数据
/*
INSERT INTO TOOL_CABINET_INVENTORY (ID, CABINET_NO, TOOL_CODE, POSITION, STATUS)
VALUES (TOOL_CABINET_INVENTORY_SEQ.NEXTVAL, '001', 'WRENCH-001', 'A1', 'in_cabinet');

INSERT INTO TOOL_CABINET_INVENTORY (ID, CABINET_NO, TOOL_CODE, POSITION, STATUS)
VALUES (TOOL_CABINET_INVENTORY_SEQ.NEXTVAL, '001', 'SCREWDRIVER-001', 'A2', 'in_cabinet');

INSERT INTO TOOL_CABINET_INVENTORY (ID, CABINET_NO, TOOL_CODE, POSITION, STATUS)
VALUES (TOOL_CABINET_INVENTORY_SEQ.NEXTVAL, '001', 'PLIERS-001', 'A3', 'in_cabinet');
*/

-- =====================================================
-- 回滚脚本（如需撤销以上操作）
-- =====================================================
/*
DROP TABLE TOOL_CABINET_SNAPSHOT CASCADE CONSTRAINTS;
DROP SEQUENCE TOOL_CABINET_SNAPSHOT_SEQ;

DROP TABLE TOOL_CABINET_INVENTORY CASCADE CONSTRAINTS;
DROP SEQUENCE TOOL_CABINET_INVENTORY_SEQ;

ALTER TABLE TOOL_INFO DROP COLUMN RECOGNITION_TYPE;
*/
