-- =====================================================
-- 工具柜系统数据初始化脚本
-- 执行时间: 2026-05-15
-- =====================================================

-- 1. 初始化 TOOL_INFO 表（工具基本信息）
-- 注意：如果表已有数据，请先清空或跳过此部分

-- 清空现有数据（可选）
-- DELETE FROM TOOL_INFO;

-- 插入扳手
INSERT INTO TOOL_INFO (TOOL_CODE, TOOL_NAME, TOOL_TYPE, STATUS, RECOGNITION_TYPE, CREATE_TIME)
VALUES ('WRENCH-001', '活动扳手', 'hand', 'AVAILABLE', 'wrench', SYSDATE);

INSERT INTO TOOL_INFO (TOOL_CODE, TOOL_NAME, TOOL_TYPE, STATUS, RECOGNITION_TYPE, CREATE_TIME)
VALUES ('WRENCH-002', '活动扳手', 'hand', 'AVAILABLE', 'wrench', SYSDATE);

INSERT INTO TOOL_INFO (TOOL_CODE, TOOL_NAME, TOOL_TYPE, STATUS, RECOGNITION_TYPE, CREATE_TIME)
VALUES ('WRENCH-003', '开口扳手', 'hand', 'AVAILABLE', 'wrench', SYSDATE);

-- 插入螺丝刀
INSERT INTO TOOL_INFO (TOOL_CODE, TOOL_NAME, TOOL_TYPE, STATUS, RECOGNITION_TYPE, CREATE_TIME)
VALUES ('SCREWDRIVER-001', '十字螺丝刀', 'hand', 'AVAILABLE', 'screwdriver', SYSDATE);

INSERT INTO TOOL_INFO (TOOL_CODE, TOOL_NAME, TOOL_TYPE, STATUS, RECOGNITION_TYPE, CREATE_TIME)
VALUES ('SCREWDRIVER-002', '一字螺丝刀', 'hand', 'AVAILABLE', 'screwdriver', SYSDATE);

INSERT INTO TOOL_INFO (TOOL_CODE, TOOL_NAME, TOOL_TYPE, STATUS, RECOGNITION_TYPE, CREATE_TIME)
VALUES ('SCREWDRIVER-003', '电动螺丝刀', 'electric', 'AVAILABLE', 'screwdriver', SYSDATE);

-- 插入钳子
INSERT INTO TOOL_INFO (TOOL_CODE, TOOL_NAME, TOOL_TYPE, STATUS, RECOGNITION_TYPE, CREATE_TIME)
VALUES ('PLIERS-001', '尖嘴钳', 'hand', 'AVAILABLE', 'pliers', SYSDATE);

INSERT INTO TOOL_INFO (TOOL_CODE, TOOL_NAME, TOOL_TYPE, STATUS, RECOGNITION_TYPE, CREATE_TIME)
VALUES ('PLIERS-002', '老虎钳', 'hand', 'AVAILABLE', 'pliers', SYSDATE);

INSERT INTO TOOL_INFO (TOOL_CODE, TOOL_NAME, TOOL_TYPE, STATUS, RECOGNITION_TYPE, CREATE_TIME)
VALUES ('PLIERS-003', '斜口钳', 'hand', 'AVAILABLE', 'pliers', SYSDATE);

-- 插入测量工具
INSERT INTO TOOL_INFO (TOOL_CODE, TOOL_NAME, TOOL_TYPE, STATUS, RECOGNITION_TYPE, CREATE_TIME)
VALUES ('MEASURING-001', '卷尺', 'measuring', 'AVAILABLE', NULL, SYSDATE);

INSERT INTO TOOL_INFO (TOOL_CODE, TOOL_NAME, TOOL_TYPE, STATUS, RECOGNITION_TYPE, CREATE_TIME)
VALUES ('MEASURING-002', '游标卡尺', 'measuring', 'AVAILABLE', NULL, SYSDATE);

COMMIT;

-- 2. 初始化 TOOL_CABINET_INVENTORY 表（工具柜库存）
-- 柜号001，共9个位置（A1-A3, B1-B3, C1-C3）

-- 清空现有数据（可选）
-- DELETE FROM TOOL_CABINET_INVENTORY;

-- 插入库存数据（将工具分配到柜子位置）
INSERT INTO TOOL_CABINET_INVENTORY (ID, CABINET_NO, TOOL_CODE, POSITION, STATUS, CREATE_TIME)
VALUES (TOOL_CABINET_INVENTORY_SEQ.NEXTVAL, '001', 'WRENCH-001', 'A1', 'in_cabinet', SYSDATE);

INSERT INTO TOOL_CABINET_INVENTORY (ID, CABINET_NO, TOOL_CODE, POSITION, STATUS, CREATE_TIME)
VALUES (TOOL_CABINET_INVENTORY_SEQ.NEXTVAL, '001', 'WRENCH-002', 'A2', 'in_cabinet', SYSDATE);

INSERT INTO TOOL_CABINET_INVENTORY (ID, CABINET_NO, TOOL_CODE, POSITION, STATUS, CREATE_TIME)
VALUES (TOOL_CABINET_INVENTORY_SEQ.NEXTVAL, '001', 'SCREWDRIVER-001', 'A3', 'in_cabinet', SYSDATE);

INSERT INTO TOOL_CABINET_INVENTORY (ID, CABINET_NO, TOOL_CODE, POSITION, STATUS, CREATE_TIME)
VALUES (TOOL_CABINET_INVENTORY_SEQ.NEXTVAL, '001', 'SCREWDRIVER-002', 'B1', 'in_cabinet', SYSDATE);

INSERT INTO TOOL_CABINET_INVENTORY (ID, CABINET_NO, TOOL_CODE, POSITION, STATUS, CREATE_TIME)
VALUES (TOOL_CABINET_INVENTORY_SEQ.NEXTVAL, '001', 'PLIERS-001', 'B2', 'in_cabinet', SYSDATE);

INSERT INTO TOOL_CABINET_INVENTORY (ID, CABINET_NO, TOOL_CODE, POSITION, STATUS, CREATE_TIME)
VALUES (TOOL_CABINET_INVENTORY_SEQ.NEXTVAL, '001', 'PLIERS-002', 'B3', 'in_cabinet', SYSDATE);

INSERT INTO TOOL_CABINET_INVENTORY (ID, CABINET_NO, TOOL_CODE, POSITION, STATUS, CREATE_TIME)
VALUES (TOOL_CABINET_INVENTORY_SEQ.NEXTVAL, '001', 'PLIERS-003', 'C1', 'in_cabinet', SYSDATE);

INSERT INTO TOOL_CABINET_INVENTORY (ID, CABINET_NO, TOOL_CODE, POSITION, STATUS, CREATE_TIME)
VALUES (TOOL_CABINET_INVENTORY_SEQ.NEXTVAL, '001', 'SCREWDRIVER-003', 'C2', 'in_cabinet', SYSDATE);

INSERT INTO TOOL_CABINET_INVENTORY (ID, CABINET_NO, TOOL_CODE, POSITION, STATUS, CREATE_TIME)
VALUES (TOOL_CABINET_INVENTORY_SEQ.NEXTVAL, '001', 'MEASURING-001', 'C3', 'in_cabinet', SYSDATE);

COMMIT;

-- 3. 验证数据
SELECT '工具信息表数据:' as info FROM DUAL;
SELECT COUNT(*) as total_count FROM TOOL_INFO;
SELECT * FROM TOOL_INFO;

SELECT '工具柜库存表数据:' as info FROM DUAL;
SELECT COUNT(*) as total_count FROM TOOL_CABINET_INVENTORY;
SELECT i.*, t.TOOL_NAME, t.TOOL_TYPE
FROM TOOL_CABINET_INVENTORY i
LEFT JOIN TOOL_INFO t ON i.TOOL_CODE = t.TOOL_CODE
ORDER BY i.CABINET_NO, i.POSITION;
